# Generated by Django 5.1.1 on 2024-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debauche',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('trigramme', models.CharField(max_length=4)),
                ('sexe', models.CharField(max_length=10)),
                ('embauche', models.DateField()),
                ('contrat', models.CharField(max_length=10)),
                ('naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=10)),
                ('metier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=80)),
                ('entite', models.CharField(max_length=10)),
                ('date_debauche', models.DateField()),
                ('motif', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Embauche',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('trigramme', models.CharField(max_length=4)),
                ('sexe', models.CharField(max_length=10)),
                ('embauche', models.DateField()),
                ('contrat', models.CharField(max_length=10)),
                ('naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=10)),
                ('metier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=80)),
                ('entite', models.CharField(max_length=10)),
                ('observation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('trigramme', models.CharField(max_length=4)),
                ('sexe', models.CharField(max_length=10)),
                ('embauche', models.DateField()),
                ('contrat', models.CharField(max_length=10)),
                ('naissance', models.DateField()),
                ('age', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=10)),
                ('metier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=80)),
                ('entite', models.CharField(max_length=10)),
            ],
        ),
    ]
