# Generated by Django 5.1.1 on 2024-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_importhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
